# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bdf8363c7b7fc9897086c9abb50b189e832e2280a424ecc54aa1363010d9be1084cbd71bcd7e087feaf33498008c68b9c1b7b9486e1e516243f550935900b47

test:
  secret_key_base: 5ee1add88d008e5b7c64b859e1239f56a3463b9f2a7da30d40b9242134b0696b1f75bde3ea8411d2d8d855291bb886d99d46b1e08bd4c710a42f8bc9abb59892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
